//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTranslator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfTranslator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;?xml version=&amp;apos;1.0&amp;apos; encoding=&amp;apos;UTF-8&amp;apos;?&amp;gt;
        ///&amp;lt;countries&amp;gt;
        ///  &amp;lt;country code=&amp;apos;af&amp;apos; handle=&amp;apos;afghanistan&amp;apos; continent=&amp;apos;asia&amp;apos; iso=&amp;apos;4&amp;apos;&amp;gt;Afghanistan&amp;lt;/country&amp;gt;
        ///  &amp;lt;country code=&amp;apos;al&amp;apos; handle=&amp;apos;albania&amp;apos; continent=&amp;apos;europe&amp;apos; iso=&amp;apos;8&amp;apos;&amp;gt;Albania&amp;lt;/country&amp;gt;
        ///  &amp;lt;country code=&amp;apos;dz&amp;apos; handle=&amp;apos;algeria&amp;apos; continent=&amp;apos;africa&amp;apos; iso=&amp;apos;12&amp;apos;&amp;gt;Algeria&amp;lt;/country&amp;gt;
        ///  &amp;lt;countr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountryListXml {
            get {
                return ResourceManager.GetString("CountryListXml", resourceCulture);
            }
        }
    }
}
